config/routes.rb
Rails.application.routes.draw do

  devise_for :users, only: :sessions
  root 'allocations#index'

  resources :users, except: :new
  resources :cars, only: [:index, :show]
  resources :allocations, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allocation.rb
class UniqAllocationValidator < ActiveModel::Validator
  def validate(record)
    allocation = Allocation.where('((start_at <= ? AND end_at >= ?) OR (start_at <= ? AND end_at >= ?)) AND car_id = ?', record.end_at, record.end_at, record.start_at, record.start_at, record.car_id)
    if allocation.exists?
      record.errors[:start_at] << "Already have an allocation for this"
    end
  end
end

class DatesAllocationValidator < ActiveModel::Validator
  def validate(record)
    if record.start_at.present? && record.end_at.present?
      if record.start_at >= record.end_at
        record.errors[:start_at] << "Period invalid, check the dates"
      end
    end
  end
end

class Allocation < ApplicationRecord
  default_scope { order(created_at: :desc) }
  belongs_to :car

  validates :document, :start_at, :end_at, presence: true
  validates_associated :car
  validates_with UniqAllocationValidator
  validates_with DatesAllocationValidator
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  default_scope { order(created_at: :desc) }
  has_many :allocations

  validates :brand, :brand_id, :model, :model_id,
    :fipe_id, :fipe_code,
    :name, :lisence_plate,
    :year_manufacture, :model_year, presence: true
  validates :model, uniqueness: {
    scope: [
      :model_id, :brand_id, :name, :lisence_plate,
      :fipe_id, :year_manufacture, :model_year
      ]
    }

  def self.brands
    uri = URI('http://fipeapi.appspot.com/api/1/carros/marcas.json')
    response = Net::HTTP.get(uri)
    response = JSON.parse(response)
    result = response.collect do|brand|
      [brand["name"], brand["id"]]
    end
    result
  end

  def self.models(brand_id)
    if brand_id.blank?
      return []
    else
      begin
        uri = URI("http://fipeapi.appspot.com/api/1/carros/veiculos/#{brand_id}.json")
        response = Net::HTTP.get(uri)
        response = JSON.parse(response)
        result = []
        response.each do |model|
          result << [model["name"], model["id"]]
        end
      rescue => exception
        result << "Error: #{exception.message}"
      end
      result
    end
  end

  def self.fipe_models(brand_id, model_id)
    if brand_id.blank? || model_id.blank?
      return []
    else
      begin
        result = []
        uri = URI("http://fipeapi.appspot.com/api/1/carros/veiculo/#{brand_id}/#{model_id}.json")
        response = Net::HTTP.get(uri)
        response = JSON.parse(response)
        response.each do |fipe_model|
          result << ["#{fipe_model["veiculo"]} :: #{fipe_model["name"]}", fipe_model["id"]]
        end
      rescue => exception
        result << "Error: #{exception.message}"
      end
      result
    end
  end

  def self.fipe_data(brand_id, model_id, fipe_id)
    uri = "http://fipeapi.appspot.com/api/1/carros/veiculo/#{brand_id}/#{model_id}/#{fipe_id}.json"
    result = []
    begin
      uri = URI(uri)
      response = Net::HTTP.get(uri)
      result = JSON.parse(response)
    rescue => exception
      logger.info exception.message
    end
    result
  end
end

app/models/concerns/fipe_api.rb
require 'net/http'
require 'json'
module FipeApi
  extend ActiveSupport::Concern

  def get_brands
    url = 'http://fipeapi.appspot.com/api/1/carros/marcas.json'
    uri = URI(url)
    response = Net::HTTP.get(uri)
    response = JSON.parse(response)
    response
  end
end

app/models/user.rb
class User < ApplicationRecord
  default_scope { order(created_at: :desc) }
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  attr_accessor :change_password

  validates :name, presence: true
end

app/controllers/allocations_controller.rb
class AllocationsController < ApplicationController
  include CableReady::Broadcaster
  skip_before_action :authenticate_user!

  def index
    @allocation = Allocation.new
    @allocations = Allocation.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @car = Car.new
    @cars = Car.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.new
  end
end

app/helpers/allocations_helper.rb
module AllocationsHelper
  def allocation_id(allocation)
    @allocation_id ||= allocation.try(:id)
  end

  def get_cars
    @get_cars ||= Car.order(brand: :asc, model: :asc, model_year: :asc).pluck(:fipe_code, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper

  def car_id(car)
    @car_id ||= car.try(:id)
  end

  def car_brand_id(car)
    @car_brand_id ||= car.try(:brand_id)
  end

  def car_model_id(car)
    @car_model_id ||= car.try(:model_id)
  end

  def car_fipe_id(car)
    @car_fipe_id ||= car.try(:car_fipe_id)
  end

  def get_brands
    @get_brands ||= Car.brands
  end

  def get_models(car)
    @get_models ||= Car.models(car_brand_id(car))
  end

  def get_fipe_models(car)
    @get_fipe_models ||= Car.fipe_models(car_brand_id(car), car_model_id(car))
  end

  def get_fipe_cars(car)
    @get_fipe_cars ||= Car.fipe_cars(car_brand_id(car), car_model_id(car), car_fipe_id(car))
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/allocations/_allocation.html.erb
<div class="card mt-2 bg-light" id="allocation-<%= allocation.id %>">
  <div class="card-header">
    <%= allocation.car.fipe_code %>
  </div>
  <div class="card-body">
    <p class="card-title text-muted">
      <table class="table">
        <thead>
          <tr class="d-flex">
            <th class="col-6">Car</th>
            <th class="col-2">Document</th>
            <th class="col-2">Start at</th>
            <th class="col-2">End at</th>
          </tr>
        </thead>
        <tbody>
          <tr class="d-flex">
            <td class="col-6"><%=allocation.car.fipe_code%></td>
            <td class="col-2"><%=allocation.document%></td>
            <td class="col-2"><%=allocation.start_at.to_formatted_s(:short)%></td>
            <td class="col-2"><%=allocation.end_at.to_formatted_s(:short)%></td>
          </tr>
        </tbody>
      </table>
      <small>Created at: <%=time_ago_in_words allocation.created_at %></small>
    </p>
    <p class="card-text lead">
      <%= button_tag 'Destroy', type: :button, data: { reflex: "click->AllocationsReflex#destroy", "allocation-id": allocation.id }, class: "btn btn-danger btn-sm" %>
    </p>
  </div>
</div>

app/views/allocations/_form.html.erb
<%= form_with model: allocation, data: { reflex: "submit->AllocationsReflex#save", controller: "allocations", "allocation-id": allocation_id(allocation) } do |f| %>
  <%= render partial: "shared/error_messages", locals: {resource: allocation} %>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :car_id, "Cars", class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.select :car_id, get_cars, {include_blank: true}, {class: 'form-control', required: true} %>
      </div>
    </div>

    <div class="col-md-6">
      <%= f.label :document, class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.text_field :document, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.label :start_at, "Start at", class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.datetime_field :start_at, class: 'form-control', required: true %>
      </div>
    </div>

    <div class="col-md-6">
      <%= f.label :end_at, "End at", class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.datetime_field :end_at, class: 'form-control', required: true %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary btn-save" %>
      </div>
    </div>
  </div>
<% end %>

app/views/allocations/index.html.erb
<h5>Allocate your Car</h5>

<div id="form-allocations">
  <%= render partial: 'form', locals: { allocation: @allocation } %>
</div>
<% if user_signed_in? %>
  <hr />
  <h5>List and actions</h5>
  <div id="allocations">
    <%= render partial: "allocation", collection: @allocations %>
  </div>
<% end %>

app/views/cars/_car.html.erb
<div class="card mt-2 bg-light" id="car-<%= car.id %>">
  <div class="card-header">
    <%= car.fipe_code %>
  </div>
  <div class="card-body">
    <p class="card-title text-muted">
      <table class="table">
        <thead>
          <tr class="d-flex">
            <th class="col-2">Brand</th>
            <th class="col-4">Model</th>
            <th class="col-2">Lisence Plate</th>
            <th class="col-2">Year Manufacture</th>
            <th class="col-2">Model Year</th>
          </tr>
        </thead>
        <tbody>
          <tr class="d-flex">
            <td class="col-2"><%=car.brand%></td>
            <td class="col-4"><%=car.model%></td>
            <td class="col-2"><%=car.lisence_plate%></td>
            <td class="col-2"><%=car.year_manufacture%></td>
            <td class="col-2"><%=car.model_year%></td>
          </tr>
        </tbody>
      </table>
      <small>Created at: <%=time_ago_in_words car.created_at %>, updated at: <%=time_ago_in_words car.updated_at %></small>
    </p>
    <p class="card-text lead">
      <%= button_tag 'Edit', type: :button, data: { reflex: "click->CarsReflex#edit", "car-id": car.id }, class: "btn btn-secondary btn-sm" %>
      <%= button_tag('Destroy', type: :button, data: { reflex: "click->CarsReflex#destroy", "car-id": car.id }, class: "btn btn-danger btn-sm") if car.allocations.empty? %>
    </p>
  </div>
</div>

app/views/cars/_fipe_models.html.erb
<% if defined?(car) %>
  <%=select :car, :fipe_id, fipe_models, {selected: car.fipe_id, include_blank: true }, {class: 'form-control', required: true, data: { brand_id: car.brand_id, model_id: car.model_id, reflex: "change->CarsReflex#get_fipe_data" }}%>
<% else %>
  <%=select :car, :fipe_id, fipe_models, {include_blank: true }, {class: 'form-control', required: true, data: { brand_id: brand_id, model_id: model_id, reflex: "change->CarsReflex#get_fipe_data" }}%>
<% end %>

app/views/cars/_form.html.erb
<%= form_with model: car, data: { reflex: "submit->CarsReflex#save", controller: "cars", "car-id": car_id(car) } do |f| %>
  <%= render partial: "shared/error_messages", locals: {resource: car} %>
  <%= f.hidden_field :brand, readonly: true %>
  <%= f.hidden_field :model, readonly: true %>
  <%= f.hidden_field :fipe_code, readonly: true %>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :brand_id, "Brands", class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.select :brand_id, get_brands, {include_blank: true}, {class: 'form-control', required: true, data: { reflex: "change->CarsReflex#get_models" }} %>
      </div>
    </div>

    <div class="col-md-6">
      <%= f.label :model_id, "Models", class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7" id="car-models">
        <%= render partial: 'models', locals: {car: car, brand_id: car_brand_id(car), models: get_models(car)} %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.label :fipe_id, "Fipe Models", class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7" id="fipe-models">
        <%= render partial: 'fipe_models', locals: {car: car, brand_id: car_brand_id(car), brand_id: car_brand_id(car), fipe_models: get_fipe_models(car)} %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.label :name, class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.text_field :name, class: 'form-control', readonly: true %>
      </div>
    </div>

    <div class="col-md-6">
      <%= f.label :lisence_plate, "Lisence Place", class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.text_field :lisence_plate, class: 'form-control', required: true %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.label :year_manufacture, "Year Manufacture", class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.text_field :year_manufacture, class: 'form-control', readonly: true %>
      </div>
    </div>

    <div class="col-md-6">
      <%= f.label :model_year, "Model Year", class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.text_field :model_year, class: 'form-control', readonly: true, required: true %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary btn-save" %>
      </div>
    </div>
  </div>
<% end %>

app/views/cars/_models.html.erb
<% if defined?(car) %>
  <%=select :car, :model_id, get_models(car), {selected: car.model_id, include_blank: true}, {class: 'form-control', required: true, data: { brand_id: car.brand_id, reflex: "change->CarsReflex#get_fipe_models" }}%>
<% else %>
  <%=select :car, :model_id, models, {include_blank: true }, {class: 'form-control', required: true, data: { brand_id: brand_id, reflex: "change->CarsReflex#get_fipe_models" }}%>
<% end %>

app/views/cars/index.html.erb
<h5>Dashboard of Cars</h5>

<div id="form-cars">
  <%= render partial: 'form', locals: { car: @car } %>
</div>
<hr />
<h5>List and actions</h5>
<div id="cars">
  <%= render partial: "car", collection: @cars %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_success_messages.html.erb
<div class="alert alert-success" role="alert">
  Operation with success
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarToYou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <div class="container h-100">
      <div class="row mt-4 justify-content-center align-items-center">
        <div class="col-12">
          <h2 id="application_title">Car to You
          <% if user_signed_in? %>
            <small><%="Hello, #{current_user.name}" %> (<span id="car-allocations"><%=Allocation.count%></span> allocations)</small>
          <% end %>
          </h2>
          <div class="btn-group mt-2" role="group" aria-label="Application Actions">
            <%= link_to "Access the Application", new_user_session_path, class:"btn btn-secondary" unless user_signed_in? %>
            <%= link_to "Allocate your Car", allocations_path, class:"btn btn-secondary" %>
            <% if user_signed_in? %>
              <%= link_to "Dashboard of Cars", cars_path, class:"btn btn-secondary" %>
              <%= link_to "Dashboard of Users", users_path, class:"btn btn-secondary" %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-secondary" %>
            <% end %>
          </div>
          <hr />
        </div>
      </div>
      <div id="success-message"><%= render partial: "layouts/success_messages" %></div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error-explanation" class="alert alert-warning">
    <h5>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h5>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user, data: { reflex: "submit->UsersReflex#save", controller: "users", "user-id": user.try(:id) } do |f| %>
  <%= render partial: "shared/error_messages", locals: {resource: user} %>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :name, class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.text_field :name, class: 'form-control', placeholder: 'name...', required: true %>
      </div>
    </div>

    <div class="col-md-6">
      <%= f.label :email, class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.email_field :email, class: 'form-control', placeholder: 'email...', required: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :password, class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-6">
      <%= f.label :password_confirmation, class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7">
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>
  </div>
  <% unless user.new_record? %>
  <div class="row">
    <div class="col-md-12 text-left">
      <%= f.label "Change password?", class: 'col-sm-5 col-form-label' %>
      <div class="col-sm-7 text-left">
        <%= f.check_box :change_password %>
      </div>
    </div>
  </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary btn-save" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="card mt-2 bg-light" id="user-<%= user.id %>">
  <div class="card-header">
    <%= user.name %>
  </div>
  <div class="card-body">
    <p class="card-title text-muted">
      E-mail: <%=user.email%><br />
      <small>Created at: <%=time_ago_in_words user.created_at %>, updated at: <%=time_ago_in_words user.updated_at %></small>
    </p>
    <p class="card-text lead">
      <%= button_tag 'Edit', type: :button, data: { reflex: "click->UsersReflex#edit", "user-id": user.id }, class: "btn btn-secondary btn-sm" %>
      <%= button_tag 'Destroy', type: :button, data: { reflex: "click->UsersReflex#destroy", "user-id": user.id }, class: "btn btn-danger btn-sm" %>
    </p>
  </div>
</div>

app/views/users/index.html.erb
<h5>Dashboard of Users</h5>

<div id="form-users">
  <%= render partial: 'form', locals: { user: @user } %>
</div>
<hr />
<h5>List and actions</h5>
<div id="users">
  <%= render partial: "user", collection: @users %>
</div>